// Auto-generated by AnimationStateMapper
public static class PlayerAnimationKeys
{
    public const string Die = "Die";
    public const string Hit = "Hit";
    public const string Idle = "Idle";
    public const string Interact = "Interact";
    public const string Run = "Run";
    public const string Jump = "Jump";
}
