// Auto-generated by AnimationStateMapper
public static class PalmonAnimationKeys
{
    public const string Attack = "Attack";
    public const string Run = "Run";
    public const string Eat = "Eat";
    public const string Idle = "Idle";
}
